Feature/ategory model
OlegMR0/book-store pull request #10
Opened 2024-01-16 02:48 UTC by OlegMR0

2024-01-17 12:50 UTC, okuzan requested changes

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/config/SecurityConfig.java
> +                        .requestMatchers("/auth/**", "/error","/auth/login",
/auth/login is redundant

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +
```suggestion

```

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/dto/mapper/UserMapper.java
> +
```suggestion
```

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/model/Category.java
> +
```suggestion
```

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/service/CategoryService.java
> +
```suggestion
```

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/service/CategoryServiceImpl.java
> +            throw new EntityNotFoundException();
add message + id

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/service/CategoryServiceImpl.java
> +        throw new EntityNotFoundException();
throw exception early (with message + id), unwrap rest of the code

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/service/CategoryServiceImpl.java
> +                .map(c -> categoryMapper.toDto(c))
avoid one letter naming in stream chains, change to category

2024-01-17 12:50 UTC, okuzan commented on src/main/java/com/example/bookstore/security/JwtService.java
> +
```suggestion
```

2024-01-17 21:31 UTC, OlegMR0 commented
![image](https://github.com/OlegMR0/book-store/assets/104794816/46746564-0d53-45e6-941c-ce82b932e605)
Do you think it's a good decision I've made handling lazy initialization? Or is there a better way?

2024-01-18 12:52 UTC, okuzan approved these changes
через join fetch це ок варіант, можеш через @EntityGraph(attributePaths = {"categories"})

2024-01-18 16:39 UTC, merged