REST Controller
OlegMR0/book-store pull request #2
Opened 2023-10-05 01:34 UTC by OlegMR0

2023-10-05 01:36 UTC, OlegMR0 commented
Help with create method please.

2023-10-05 12:31 UTC, okuzan requested changes
One field was missing

2023-10-05 12:31 UTC, okuzan commented on src/main/java/com/example/bookstore/service/BookServiceImpl.java
> +                .orElseThrow(EntityNotFoundException::new));
add id to the message

2023-10-05 12:31 UTC, okuzan commented on src/main/java/com/example/bookstore/service/BookService.java
> +    BookDto findById(Long id);
you need only one

2023-10-05 12:31 UTC, okuzan commented on src/main/java/com/example/bookstore/service/BookServiceImpl.java
>      }
use findById instead

2023-10-05 12:31 UTC, okuzan commented on src/main/java/com/example/bookstore/dto/CreateBookRequestDto.java
> +    private BigDecimal price;
add isbn
rebuild project so mapper can accommodate this change
![image](https://github.com/OlegMR0/book-store/assets/49767049/4cbc8be0-2753-4939-bcd1-49389893dc45)

2023-10-05 12:31 UTC, okuzan commented on src/main/java/com/example/bookstore/controller/BookController.java
> +
remove line

2023-10-05 12:31 UTC, okuzan commented on src/main/java/com/example/bookstore/controller/BookController.java
> +    @GetMapping()
```suggestion
    @GetMapping

```

2023-10-05 12:31 UTC, okuzan commented on src/main/java/com/example/bookstore/controller/BookController.java
> +    @PostMapping()
```suggestion
    @PostMapping

```

2023-10-06 11:19 UTC, olekskov commented on pom.xml
> +        </dependency>
why we need this dependency?

2023-10-06 12:47 UTC, merged