Feature/searching
OlegMR0/book-store pull request #3
Opened 2023-10-16 01:31 UTC by OlegMR0

2023-10-16 14:11 UTC, Rommelua requested changes

2023-10-16 14:11 UTC, Rommelua commented on src/main/java/com/example/bookstore/repository/book/PriceSpecificationProvider.java
> +                return root.get(FIELD_SPECIFICATION).in(params);
How is it possible to have a list of price values? You should have min/max price boundaries

2023-10-16 14:11 UTC, Rommelua commented on src/main/java/com/example/bookstore/repository/book/TitleSpecificationProvider.java
> +                return root.get(FIELD_SPECIFICATION).in(params);
Len's implement 'contains' logic for Title

2023-10-16 14:11 UTC, Rommelua commented on src/main/java/com/example/bookstore/service/BookServiceImpl.java
> +        if (bookRepository.findById(id).isPresent()) {
use `existsById(id)`

2023-10-17 21:44 UTC, merged

2023-11-07 09:34 UTC, Sanderfuck reviewed
Check comments

2023-11-07 09:34 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/repository/BookSpecificationBuilder.java
> +        return specification;
Use constants

2023-11-07 09:34 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/repository/BookSpecificationProviderManager.java
> +            + "specification provider for this key ";
Try to use String format

2023-11-07 13:55 UTC, OlegMR0 commented
#6