Global exception handler and data validation
OlegMR0/book-store pull request #4
Opened 2023-10-20 01:39 UTC by OlegMR0

2023-10-20 01:41 UTC, OlegMR0 commented
Please help me to fix.
It should work, but output in postman is the same
![image](https://github.com/OlegMR0/book-store/assets/104794816/c7da4c98-b523-49a9-8291-e7132f57bf24)

2023-10-20 17:51 UTC, okuzan requested changes
Need further details

2023-10-20 17:51 UTC, okuzan commented on src/main/java/com/example/bookstore/exception/GlobalExceptionHandler.java
> +    @Override
you can also add
```
    @ExceptionHandler(EntityNotFoundException.class)
    protected ResponseEntity<Object> handleEntityNotFoundException(EntityNotFoundException ex) {
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("timestamp", LocalDateTime.now().format(FORMATTER));
        body.put("status", HttpStatus.NOT_FOUND);
        body.put("error", "Entity Not Found");
        body.put("message", ex.getMessage());
        return new ResponseEntity<>(body, HttpStatus.NOT_FOUND);
    }
```

2023-10-22 15:08 UTC, Ivan95kos approved these changes
Great job

2023-10-24 11:54 UTC, merged